### ISSUE TITLE
Add several folders to gitignore

### ISSUE THREAD

**Issue by alt3d** [fidt17/Colony-Simulator#2]
You should exclude "library" folder from git
This folder can be recreated from assets
Same things with the "logs" and other folders

All you need under git control is "assets", "packages" and "project settings" folders

**Comment by fidt17** [comment]
Thank you for this information! I will definitely look into it a bit later.

**Comment by fidt17** [comment]
.gitignore seems to be working fine now.
I did need to tweak my folders' arrangement a bit though.
From now on, I don't need to upload all the unnecessary data, and the uploading time has gone down drastically.
Thank you a lot, @alt3d!
